version: 0.1

phases:
  build:
    commands:
      - aws deploy push --region ap-northeast-1 --application-name aws-udemy-14days-simple-blog --s3-location s3://aws-udemy-codebuild-artifact-hyoshioka/sample.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
  name: sample.zip
